[build-system]
requires = ["setuptools>=75"]
build-backend = "setuptools.build_meta"

[project]
name = "greater-manchester-flood-monitoring-data-platform"
version = "0.1.0"
description = "Greater Manchester Flood and River Monitoring ETL and Reporting Platform."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "requests>=2.32",
    "pandas>=2.2",
    "python-dotenv>=1.0"
]

[project.optional-dependencies]
dev = [
    "pytest>=8.0"
]

[tool.setuptools.packages.find]
where = ["src"]
